import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../scss/style.scss";
import { Providers } from "@/redux/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
